default:
  dict_example: "https://github.com/pzhaonet/pinyin/raw/master/inst2/wubi86.txt"
  token_url: "https://chinaeast2.api.cognitive.azure.cn/sts/v1.0/issueToken"
  tts_url: "https://chinaeast2.tts.speech.azure.cn/cognitiveservices/v1"
  stt_url: "https://chinaeast2.stt.speech.azure.cn/speech/recognition/conversation/cognitiveservices/v1?language=en-US&format=detailed&profanity=raw"
  subscription_key: "my_key"
